#!/usr/bin/env bash

tmp=`mktemp`
basename="net/twitter-2010"
wg="wg"

java -Xmx4000m -cp .:$wg/* ReduceGraph $basename $1 $3 > $tmp
gcc -Wall -Ofast -march=native -funroll-loops -fopenmp -ftree-vectorizer-verbose=0 -funsafe-loop-optimizations -falign-functions=16 -falign-loops=16 \
-DDRIVERPERC=$2 -DSEED=$3ULL -include types.h -include $tmp *.c -o /tmp/$1-$2-$3
rm $tmp
