#define CARCOST 100
#define TICKETCOST 300
#define PENNYPERLITRE 130
#define METERSPERLITRE 15000
#define MAXDRIVERS 1
#define EPSILON 0.05
#define DRIVERPERC 10
#define MINGAIN 1

#define REORDER
//#define PARALLEL
//#define NAIVE
