#!/usr/bin/env bash

if [ "$#" -eq 0 ]
then
	echo "usage: ./partest N D MAXLIMIT NTESTS OUTDIR"
	exit
fi

cores=`grep -c ^processor /proc/cpuinfo`
seeds=""

for t in `seq 1 $4`
do
	seeds="$seeds$RANDOM$RANDOM "
done

echo $seeds | xargs -n 1 --max-procs=$(( $cores / 2 )) ./compile $1 $2 $3
echo $seeds | xargs -n 1 --max-procs=$cores ./run $1 $2 $3 $5/$1-$2
