#!/usr/bin/env bash

if [ "$#" -eq 0 ]
then
	echo "usage: ./partest N NTESTS OUTDIR"
	exit
fi

cores=`grep -c ^processor /proc/cpuinfo`
seeds=""

for t in `seq 1 $2`
do
	seeds="$seeds$t "
done

echo $seeds | xargs -n 1 --max-procs=$(( $cores / 2 )) ./compile $1
echo $seeds | xargs -n 1 --max-procs=1 ./run $1 $3/$1.csv
